# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "ttyd.names.fullname" (dict "root" $ "name" "startup") }}"
data:
  {{- required "Startup config not set. Please set .Values.startup.config" .Values.startup.config | nindent 2 }}
---
