apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "certs.secretName.cf" . }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  "{{ .Values.cf.secrets.key }}": "{{ required "Cloudflare API token not provided. Please set .Values.cf.secrets.apiToken" .Values.cf.secrets.apiToken }}"
