apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.ingress.mtlsCaName }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ include "certs.namespaces" . }}
type: kubernetes.io/tls
data:
  tls.crt: "{{ required "Lab CA cert not set. Please set .Values.lab.secrets.ca.cert" .Values.lab.secrets.ca.cert | b64enc }}"
  tls.key: "{{ required "Lab CA key not set. Please set .Values.lab.secrets.ca.key" .Values.lab.secrets.ca.key | b64enc }}"
