apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "certs-chart.fullname.cf" . }}"
  # namespace: "{{ .Release.Namespace }}"
spec:
  secretName: "{{ .Values.cf.secrets.certSecretName }}"
  issuerRef:
    name: "{{ include "certs-chart.clusterIssuers.cf" . }}"
    kind: ClusterIssuer
  dnsNames:
    {{- .Values.cf.dnsNames | toYaml | nindent 4 }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ include "certs-chart.namespaces" . }}"
