apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "jellyfin-chart.fullname" . }}"
spec:
  selector:
    matchLabels:
      {{- include "jellyfin-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin-chart.selectorLabels" . | nindent 8 }}
    spec:
      hostnameOverride: jellyfin
      containers:
      - name: jellyfin
        image: "{{ printf "%s:%s" .Values.image.repository .Values.image.tag }}"
        ports:
        {{- range $key, $_ := .Values.ports }}
          - name: "{{ $key }}"
            containerPort: {{ .port }}
            protocol: "{{ .protocol }}"
        {{- end }}
        volumeMounts:
        {{- range $key, $_ := .Values.volumes }}
          - name: "{{ $key }}"
            mountPath: "{{ .mountPath }}"
        {{- end }}
        securityContext:
          privileged: true
      volumes:
      {{- range $key, $_ := .Values.volumes }}
        - name: "{{ $key }}"
          {{- .source | toYaml | nindent 10 }}
      {{- end }}
