apiVersion: v1
kind: Service
metadata:
  name: "{{ include "jellyfin-chart.fullname" . }}"
spec:
  selector:
    {{- include "jellyfin-chart.selectorLabels" . | nindent 6 }}
  ports:
  {{- range $key, $_ := .Values.ports }}
    - name: "{{ $key }}"
      targetPort: {{ .port }}
      port: {{ .port }}
  {{- end }}

