apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
spec:
  selector:
    matchLabels:
      app: jellyfin-app
  template:
    metadata:
      labels:
        app: jellyfin-app
    spec:
      containers:
      - name: jellyfin-app
        image: ghcr.io/linuxserver/jellyfin
        ports:
        - containerPort: 8096
