# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
spec:
  storageClassName: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-pvc
spec:
  storageClassName: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Mi
---
