apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingress-certificate
spec:
  secretName: nginx-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.aramismatos1.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,dns,vpn"
