# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-app
  labels:
    app: startup-app
spec:
  selector:
    matchLabels:
      app: startup-app
  template:
    metadata:
      labels:
        app: startup-app
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: startup-app
        image: aramismatos/wake-on-lan:wol-test
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
        envFrom:
          - configMapRef:
              name: startup-config
        ports:
        - containerPort: 3001
          name: startup-app
      restartPolicy: Always
---

