# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-app
  labels:
    app: startup-app
spec:
  selector:
    matchLabels:
      app: startup-app
  template:
    metadata:
      labels:
        app: startup-app
    spec:
      containers:
      - name: startup-app
        image: aramismatos/wake-on-lan:latest
        envFrom:
          - configMapRef:
              name: startup-config
        ports:
        - containerPort: 3001
          name: startup-app
      restartPolicy: Always
---

