# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
let
  username = import ./system/users/name.nix;
  massStorage = "/dev/disk/by-uuid/54196560-2008-474d-9258-27847487b39c";
  massStorageLoc = "/home/${username}/mass_storage";
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/44532b14-f069-464a-8e83-dda1e5a083dc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C4C1-4C70";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."${massStorageLoc}" = {
    device = massStorage;
    fsType = "ext4";
  };

  fileSystems."/export/Downloads" = {
    device = "${massStorageLoc}/Downloads/k8s-downloads";
    options = [ "bind" ];
  };

  boot.supportedFilesystems = [ "nfs" ];

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
