apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "vpn.secret" (dict "root" $ "name" "vpn") }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  wireguard-addresses: "{{ required "WireGuard addresses not set. Please set .Values.gluetun.secrets.addresses.value" .Values.gluetun.secrets.addresses.value }}"
  wireguard-private-key: "{{ required "WireGuard private key not set. Please set .Values.gluetun.secrets.privateKey.value" .Values.gluetun.secrets.privateKey.value }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "vpn.secret" (dict "root" $ "name" .Values.slskd.config.name) }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  "{{ .Values.slskd.config.key }}": |-
    {{- required "Slskd config not set. Please set .Values.slskd.config.value" .Values.slskd.config.value | nindent 4 }}

