# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "dns.pihole.pvc" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "dns.pihole.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

