#!/nix/store/v8sa6r6q037ihghxfbwzjj4p59v2x0pv-bash-5.3p9/bin/bash
set -e

namespaces=("default" "kube-system" "cert-manager" "longhorn-system" "dns")

KUBECONFIG="$HOME/k3s.yaml"

for namespace in "${namespaces[@]}"; do
    /nix/store/6m48j0x1w9hq9l6byqcnj82q5h0c6nbg-kubectl-1.35.3/bin/kubectl --kubeconfig "$KUBECONFIG" -n "$namespace" get po | \
    grep -vE '(NAME|Running|Terminating)' | \
    /nix/store/gg169kyil5vhsg5aqcpagyhs8fwl0r5r-gawk-5.3.2/bin/awk '{print $1}' | \
    xargs -I % kubectl --kubeconfig "$KUBECONFIG"  -n "$namespace" delete pod %;
done


