# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dns.bind9.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  home.lab.zone: |
    {{- required "BIND9 config not set. Please set .Values.bind9.secrets.zoneValue" .Values.bind9.secrets.zoneValue | nindent 4 }}
  named.conf: |
    {{- required "BIND9 config not set. Please set .Values.bind9.secrets.namedConfValue" .Values.bind9.secrets.namedConfValue | nindent 4 }}
