# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "dns.pihole.fullname" . }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  password: "{{ required "PiHole password required. Please set .Values.pihole.secrets.value in plain-text" .Values.pihole.secrets.value | b64enc }}"
