apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ddclient.conf: |-
    {{-  required "DDClient config not loaded, please set .Values.secrets.secret" .Values.secrets.secret | nindent 4 }}
